---
- name: install
  hosts: localhost
  vars:
    ruby_version: 2.2.3
    local_home: "{{ lookup('env','HOME') }}"

  tasks:
  - name: Install Java tools
    homebrew_cask: name=java state=present

  - name: Install my personal tap
    homebrew_tap: tap=deluan/tap state=present

  - name: Install DuckDns client tap
    homebrew_tap: tap=jzelinskie/duckdns state=present

  - name: Install basic tools using brew
    homebrew: 
      name: ['wget', 'jq', 'git', 'gawk', 'mercurial', 'gradle', 'fzf', 'direnv', 'go', 'hugo', 'tree', 'duckdns', 'zsh', 'zplug']

  # - name: Add ZSH to allowed shells
  #   lineinfile: 
  #     path: /etc/shells
  #     line: /usr/local/bin/zsh
  #   become: true

  # - name: Set ZSH as default shell
  #   shell: dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
  #   become: root

  - name: Install Zplug
    git:
      repo: https://github.com/zplug/zplug
      dest: ~/.zplug
      update: no

  - name: Creates .ssh folder
    shell: mkdir ~/.ssh creates=~/.ssh

  - name: Install gst script
    copy: src=./files/gst dest=~/bin/gst mode=0755

  - name: Install dotfiles
    synchronize: 
      src: dotfiles/
      dest: ~/ 
      archive: yes 
      checksum: yes
      times: no
      rsync_opts:
        - "--exclude=.zshrc"

  - name: Install .zshrc
    file:
      src: $PWD/dotfiles/.zshrc
      dest: ~/.zshrc
      state: link
      force: yes

  - name: Install RVM
    shell: curl -L https://get.rvm.io | bash -s stable --ruby={{ruby_version}} --ignore-dotfiles creates=~/.rvm/scripts/rvm

  - name: Install FNM
    homebrew: name=Schniz/tap/fnm state=present

  - name: Create bin folder
    file: path=~/bin state=directory

  - name: Install Grails.sh
    homebrew: name=grails.sh state=present

  - name: Install Fonts tap
    homebrew_tap: name=homebrew/cask-fonts state=present

  - name: Install Homebrew Cask
    shell: brew tap caskroom/cask creates=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask

  - name: Install Dev tools using brew cask
    homebrew_cask: name={{item}} state=present
    with_items: [font-fira-code]

  # - name: Install Other Applications using brew cask
  #   homebrew_cask: name={{item}} state=present
  #   with_items: [google-chrome, iterm2-nightly, handbrake, vlc, transmission, 
  #     disk-inventory-x, flux, calibre, visual-studio-code, sourcetree
  #     1password, intellij-idea, plex-media-player, screenhero, mysqlworkbench,
  #     dropbox, bittorrent-sync, atom, iconping, virtualbox, vagrant, bitbar]
