---
- name: install
  hosts: localhost
  vars:
    ruby_version: 2.2.3
    node_version: 0.10.21
    local_home: "{{ lookup('env','HOME') }}"

  tasks:
  - name: Install basic tools using brew
    homebrew: name={{item}} state=present
    with_items: [wget, jq, git, gawk, mercurial, gradle]

  - name: Creates .ssh folder
    shell: mkdir ~/.ssh creates=~/.ssh

  - name: Install Vagrant Insecure Private Key
    copy: src=./files/vagrant_rsa dest=~/.ssh/vagrant_rsa mode=0600

  - name: Install profile.d scripts
    synchronize: src=.profile.d dest=~/ delete=yes archive=yes checksum=yes times=no

  - name: Install dotfiles
    synchronize: src=dotfiles/ dest=~/ archive=yes checksum=yes times=no

  - name: Install RVM
    shell: curl -L https://get.rvm.io | bash -s stable --ruby={{ruby_version}} creates=~/.rvm/scripts/rvm

  - name: Install NVM
    git: repo=https://github.com/creationix/nvm.git dest=~/.nvm update=no

  - name: Install Node
    shell: source ~/.nvm/nvm.sh && nvm install {{node_version}} && nvm alias default {{node_version}} creates=~/.nvm/alias/default

  - name: Install DCD
    npm: executable={{local_home}}/.nvm/v{{node_version}}/bin/npm name=dcd global=yes

  - name: Create bin folder
    file: path=~/bin state=directory

  - name: Install my personal tap
    homebrew_tap: tap=deluan/tap state=present

  - name: Install Grails.sh
    homebrew: name=grails.sh state=present

  - name: Install Bash Autocompletion
    homebrew: name=bash-completion state=present

  - name: Install Autocompletion tap
    homebrew_tap: tap=homebrew/completions state=present
