#!/bin/bash

# Install HomeBrew
which brew || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install Ansible
which ansible || brew install ansible

# Provision everything else
ansible-playbook install.yaml
