---
- name: install
  hosts: localhost
  vars:
    ruby_version: 1.9.3
    node_version: 0.10.21
    local_home: "{{ lookup('env','HOME') }}"

  tasks:
  - name: Install wget
    homebrew: name=wget state=present

  - name: Install jq
    homebrew: name=jq state=present

  - name: Install mercurial
    homebrew: name=mercurial state=present

  - name: Creates .ssh folder
    shell: mkdir ~/.ssh creates=~/.ssh

  - name: Install Vagrant Insecure Private Key
    copy: src=./files/vagrant_rsa dest=~/.ssh/vagrant_rsa mode=0600

  - name: Install profile.d scripts
    synchronize: src=.profile.d dest=~/ delete=yes archive=yes

  - name: Install dotfiles
    shell: cp dotfiles/.[^.]* ~

  - name: Install RVM
    shell: curl -L https://get.rvm.io | bash -s stable --ruby={{ruby_version}} creates=~/.rvm/scripts/rvm

  - name: Install NVM
    git: repo=https://github.com/creationix/nvm.git dest=~/.nvm update=no

  - name: Install Node
    shell: source ~/.nvm/nvm.sh && nvm install {{node_version}} && nvm alias default {{node_version}} creates=~/.nvm/alias/default

  - name: Install DCD
    npm: executable={{local_home}}/.nvm/v{{node_version}}/bin/npm name=dcd global=yes

  - name: Create bin folder
    file: path=~/bin state=directory

  - name: Download Grails.sh
    get_url: url=https://raw.githubusercontent.com/deluan/grails.sh/master/grails dest=~/bin/grails

  - name: Install Grails.sh
    file: path=~/bin/grails mode=ugo+rx
