#!/bin/bash

# Install HomeBrew
if ! which brew; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew tap deluan/tap
fi

# Install Ansible
if ! which ansible; then
  brew install ansible
fi

ansible-playbook install.yaml
