#!/bin/bash

RED="\033[0;31m"
YELLOW="\033[0;33m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
NC="\033[0m"

for i in `find . -name '.git' -type d` ; do
	(
    dir=`dirname $i | cut -c3-300`
    cd $dir

		RES=$(git status 2>/dev/null| grep -E '^(Changes|Changed|Untracked)')
		STAT=""
		grep -e 'Untracked' <<<${RES} >/dev/null 2>&1
		if [ $? -eq 0 ] ; then
			STAT="${GREEN}U${NC}"
		else
			STAT=" "
		fi
		grep -e 'Changed' <<<${RES} >/dev/null 2>&1
		if [ $? -eq 0 ] ; then
			STAT="$STAT${YELLOW}M${NC}"
		else
			STAT="$STAT "
		fi
		grep -e 'Changes' <<<${RES} >/dev/null 2>&1
		if [ $? -eq 0 ] ; then
			STAT="$STAT${RED}S${NC}"
		else
			STAT="$STAT "
		fi

		if [[ ! $STAT =~ ^\ +$ ]] ; then
			echo -e "$STAT : $dir"
		fi
	)
done
