#!/bin/bash

RED="\033[0;31m"
YELLOW="\033[0;33m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
NC="\033[0m"

STAT=""
check() {
	grep -e "$1" <<<${RES} >/dev/null 2>&1
	if [ $? -eq 0 ] ; then
		STAT="$STAT$2$3${NC}"
	else
		STAT="$STAT "
	fi
}

for i in `find . -name '.git' -type d` ; do
	(
    dir=`dirname $i | cut -c3-300`
    cd $dir > /dev/null

		RES=$(git status 2>/dev/null| grep -E '^(Changes to|Changes not|Untracked|Your branch is ahead)')

		check 'Changes to' $GREEN 'S'
		check 'Changes not' $YELLOW 'C'
		check 'Untracked' $RED 'U'
		check 'Your branch is ahead' $BLUE '↑'

		if [[ ! $STAT =~ ^\ +$ ]] ; then
			echo -e "$STAT : $dir"
		fi
	)
done
